" Remove start up nag screen
set shortmess+=I
set mouse=nvc
if $TERM =~# '^nsterm\|^st\|^tmux'
	" Better mouse support for dragging
	set ttymouse=sgr
endif

colorscheme chromatine
set splitbelow splitright

if executable('ag')
	set grepprg=ag\ --vimgrep\ $* grepformat=%f:%l:%c:%m
endif
if &t_Co > 2 || has('gui_running')
	set hlsearch
endif
set ignorecase smartcase

" Allow unsaved buffers
set hidden
" Do not let random files mess with the settings
set nomodeline
" Copy the file then save it (useful for some filesystem watch mechanisms)
set backupcopy=yes
set autoread

set noswapfile
set viminfo=

" Status line {{{
""" Sample status line:
" [23] .dotfiles/.vim/vimrc [+]                   [dos] 10, 70/218
" [23] options.txt [Help][-][RO]                        10, 70/218
set statusline=
set statusline+=\ [%n]
set statusline+=\ %<%f
set statusline+=\ %h%w%m%r
set statusline+=%=
set statusline+=%{&ff!='unix'?'['.&ff.']\ ':''}
set statusline+=%-14.(%l,%c%V%)\ %(%L\ %)
set showtabline=2
" }}}

" netrw {{{
let g:netrw_dirhistmax=0
let g:netrw_banner=0
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
" }}}

" So syntax highlighting understands $(...)
let g:is_posix = 1
let g:tmux_syntax_colors = 0

if has('autocmd')
	augroup vimrc_autocmd
		autocmd!

		autocmd FileType gitcommit,gitsendmail,mail,markdown,text
			\ setlocal spell spelllang=en_gb expandtab
			         \ shiftwidth=2 softtabstop=2
		if executable('par')
			autocmd FileType gitcommit,gitsendmail,mail,markdown,text
			      \ let &l:formatprg = 'par -w' .
			      \ (&textwidth > 0 ? &textwidth : 74)
		endif

		autocmd FileType
		      \ css,javascript,javascriptreact,json,sass,scss,typescript,typescriptreact
		      \ setlocal expandtab shiftwidth=2 softtabstop=2
	augroup END
endif

" casr/vim-colors-chromatine
" tpope/vim-apathy
" tpope/vim-commentary
" tpope/vim-eunuch
" tpope/vim-rsi
" tpope/vim-sensible
" tpope/vim-unimpaired
