set encoding=utf-8
scriptencoding utf-8

set autoindent
set background=light
set backupcopy=yes
set belloff=all
set breakindent
set breakindentopt=list:-1,sbr,shift:2
set colorcolumn=+1
set comments+=fb:•
set commentstring=
set completeopt=menuone,popup,noselect
set expandtab
set fillchars=fold:·,foldopen:┌,foldclose:╓,foldsep:│,vert:│
let &foldcolumn=has('nvim') ? 'auto:4' : '1'
set foldlevelstart=99
set formatoptions+=nor
set hidden
set history=10000
set hlsearch
set ignorecase
set incsearch
set nojoinspaces
set linebreak
set list
set listchars=tab:›\ ,trail:•,extends:›,precedes:‹,nbsp:.
set nomodeline
set mouse=cnv
set number
set pumheight=10
set shiftwidth=2
set shortmess+=CFI shortmess-=S
set showbreak=\ 
set showcmd
set showtabline=2
let &signcolumn=has('nvim') ? 'auto:2-4' : 'yes'
set smartcase
set softtabstop=-1
set splitbelow
set splitkeep=screen
set splitright
set nostartofline
set noswapfile
set switchbuf=uselast
set undofile
set updatetime=400
set wildmode=longest:full,full
set wildoptions=pum,tagfile

" The Vim that ships with MacOS only supports external diff. Therefore only
" set improved options when internal is present.
if &diffopt =~# 'internal'
  set diffopt+=algorithm:histogram,indent-heuristic,linematch:60
endif

" MacOS' Vim defaults regexpengine to the old engine in contrast to stock Vim
if &regexpengine ==# 1
  set regexpengine=0
endif

if has('nvim')
  set winborder=rounded
endif

if executable('rg')
  set grepformat=%f:%l:%c:%m
  set grepprg=rg\ --vimgrep\ -uu
else
  set grepformat=%f:%l:%m
  set grepprg=grep\ -InHR\ --exclude-dir=.git
endif

if has('nvim') | finish | endif

if exists('*mkdir')
  let &backupdir=simplify(fnamemodify($MYVIMRC, ':p:h') . '/backup')
  let &undodir=simplify(fnamemodify($MYVIMRC, ':p:h') . '/undo')

  if !isdirectory(&undodir)
    call mkdir(&undodir, 'p', 0700)
  endif

  if !isdirectory(&backupdir)
    call mkdir(&backupdir, 'p', 0700)
  endif
endif

if has('viminfo')
  set viminfo^=r/tmp/ viminfo^=r/private/
  let &viminfo=&viminfo . ',n' .
        \ simplify(fnamemodify($MYVIMRC, ':h') . '/info')
endif

packadd! editorconfig
