local r_treesitter, treesitter = pcall(require, "nvim-treesitter.configs")

if not r_treesitter then
  return
end

treesitter.setup({
  parser_install_dir = vim.fn.stdpath("data") .. "/site",
  highlight = { enable = true },
  indent = { enable = true },
  modules = {},
  sync_install = true,
  auto_install = false,
  ensure_installed = {
    "bash",
    "c",
    "css",
    "diff",
    "dockerfile",
    "editorconfig",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "glsl",
    "graphql",
    "hlsl",
    "html",
    "ini",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "ledger",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "rust",
    "scss",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
  },
  ignore_install = {},
})
