#!/usr/bin/env zsh

# psvar[5]: human readable elapsed command time

prompt_corrupt_human_time() {
	integer total_seconds="$1"
	integer days=$(( total_seconds / 60 / 60 / 24 ))
	integer hours=$(( total_seconds / 60 / 60 % 24 ))
	integer minutes=$(( total_seconds / 60 % 60 ))
	integer seconds=$(( total_seconds % 60 ))

	local output=""
	integer cascade=0
	(( days > 0 )) && output+="${days}d " cascade=1
	(( hours > 0 || cascade )) && output+="${hours}h " cascade=1
	(( minutes > 0 || cascade )) && output+="${minutes}m "
	print -- "${output}${seconds}s"
}

prompt_corrupt_precmd() {
	local git_action git_branch runtime
	local -at ps1 rps1 top_line

	psvar[5]=
	if [[ -n "${prompt_corrupt_cmd_start_time}" ]]; then
		local cmd_elapsed_time=$(( SECONDS - prompt_corrupt_cmd_start_time ))
		if (( cmd_elapsed_time >= 5 )); then
			psvar[5]=$(prompt_corrupt_human_time "${cmd_elapsed_time}")
		fi
	fi
	prompt_corrupt_cmd_start_time=

	vcs_info

	if [ -n "${vcs_info_msg_0_}" ]; then
		git_branch="%8F⺦%f${vcs_info_msg_0_}"
	fi

	if [ -n "${vcs_info_msg_1_}" ]; then
		git_action="%8F${vcs_info_msg_1_}%f"
	fi

	top_line=(
		# the current path
		' %~'
	)

	if [ "${VIRTUAL_ENV+yes}" = yes ]; then
		top_line+=(
			'${VIRTUAL_ENV+%8F●%f${VIRTUAL_ENV##*/}}'
		)
	fi

	top_line+=(
		"${git_branch}"
		"${git_action}"
	)

	ps1=(
		"${(@j.  .)top_line:#}"
		$prompt_newline
		# Indicate if user is running with privileges. i.e. root. If
		# there is a job running in the background, prefix an asterisk
		'%(1j.*. )%(!.#.$) '
	)

	rps1=(
		'%5v'
		'%8F%*%f'
	)

	# a gap between the last command's output is nice
	print

	# man zshmisc /EXPANSION OF PROMPT SEQUENCES
	PS1="${(j..)ps1}"
	RPS1="${(j. .)rps1}"
}

prompt_corrupt_preexec() {
	prompt_corrupt_cmd_start_time=${prompt_corrupt_cmd_start_time:-$SECONDS}
}

prompt_corrupt_setup() {
	add-zsh-hook precmd prompt_corrupt_precmd
	add-zsh-hook preexec prompt_corrupt_preexec

	# man zshcontrib /GATHERING INFORMATION FROM VERSION CONTROL SYSTEMS
	autoload -Uz vcs_info
	zstyle ':vcs_info:*' enable git
	zstyle ':vcs_info:*' use-simple true
	zstyle ':vcs_info:*' max-exports 2
	zstyle ':vcs_info:*' formats '%b'
	zstyle ':vcs_info:*' actionformats '%b' '%a'

	prompt_opts=(cr sp percent subst)
}

prompt_corrupt_setup "$@"
