#!/usr/bin/env zsh

# psvar[4]: time command started
# psvar[5]: human readable elapsed command time
# psvar[6]: vcs branch
# psvar[7]: vcs action
# psvar[8]: virtual environment

prompt_corrupt_human_time() {
	integer total_seconds="$1"
	integer days=$(( total_seconds / 60 / 60 / 24 ))
	integer hours=$(( total_seconds / 60 / 60 % 24 ))
	integer minutes=$(( total_seconds / 60 % 60 ))
	integer seconds=$(( total_seconds % 60 ))

	local output=""
	integer cascade=0
	(( days > 0 )) && output+="${days}d " cascade=1
	(( hours > 0 || cascade )) && output+="${hours}h " cascade=1
	(( minutes > 0 || cascade )) && output+="${minutes}m "
	print -- "${output}${seconds}s"
}

prompt_corrupt_precmd() {
	psvar[5]=
	if [[ -n "${psvar[4]}" ]]; then
		local cmd_elapsed_time=$(( SECONDS - psvar[4] ))
		if (( cmd_elapsed_time >= 5 )); then
			psvar[5]=$(prompt_corrupt_human_time "${cmd_elapsed_time}")
		fi
	fi
	psvar[4]=

	psvar[6]=
	psvar[7]=
	vcs_info
	# vcs branch
	[[ -n "${vcs_info_msg_0_}" ]] && psvar[6]="${vcs_info_msg_0_}"
	# vcs action
	[[ -n "${vcs_info_msg_1_}" ]] && psvar[7]="${vcs_info_msg_1_}"

	psvar[8]=
	if [[ -n "${CONDA_DEFAULT_ENV}" ]]; then
		psvar[8]="${CONDA_DEFAULT_ENV:t}"
	fi
	if [[ -n "${VIRTUAL_ENV}" ]]; then
		psvar[8]="${VIRTUAL_ENV:t}"
	fi

	# a gap between the last command's output is nice
	print
}

prompt_corrupt_preexec() {
	psvar[4]=${psvar[4]:-$SECONDS}
}

prompt_corrupt_setup() {
	add-zsh-hook precmd prompt_corrupt_precmd
	add-zsh-hook preexec prompt_corrupt_preexec

	# man zshcontrib /GATHERING INFORMATION FROM VERSION CONTROL SYSTEMS
	autoload -Uz vcs_info
	zstyle ':vcs_info:*' enable git
	zstyle ':vcs_info:*' use-simple true
	zstyle ':vcs_info:*' max-exports 2
	zstyle ':vcs_info:*' formats '%b'
	zstyle ':vcs_info:*' actionformats '%b' '%a'

	# man zshmisc /EXPANSION OF PROMPT SEQUENCES
	PS1=
	# background jobs
	PS1+='%(2j.%j.)%(1j.*  .)'
	# time
	PS1+='%8F%D{%H:%M}%f'
	# time command took
	PS1+='%(5V.  %5v.)'
	# the current path
	PS1+='  %~'
	# virtualenv
	PS1+='%(8V.  %8Fvenv(%f%8v%8F)%f.)'
	# vcs branch
	PS1+='%(6V.  %8Fgit(%f%6v%8F)%f.)'
	# vcs action
	PS1+='%(7V.  %8F%7v%f.)'
	PS1+="${prompt_newline}"
	# Indicate if user is running with privileges. i.e. root. Highlight
	# prompt if previous command fails
	PS1+='%(?.%f.%1F)%(!.#.$)%f '

	prompt_opts=(cr sp percent)
}

prompt_corrupt_setup "$@"
