[colors.selection]
text = "CellForeground"
background = "#005F87"

[colors.primary]
foreground = "#dadada"
background = "#1c1c1c"

[colors.normal]
black = "#303030"
red = "#af5f5f"
green = "#87af87"
yellow = "#ffd787"
blue = "#5f5faf"
magenta = "#af87af"
cyan = "#87afaf"
white = "#dadada"

[colors.bright]
black = "#767676"
red = "#af5f5f"
green = "#87af87"
yellow = "#ffd787"
blue = "#5f5faf"
magenta = "#af87af"
cyan = "#87afaf"
white = "#e4e4e4"

[bell]
animation = "EaseOutQuad"
duration = 200
color = "#000000"
