[colors.cursor]
text = "CellForeground"
cursor = "#005f5f"

[colors.selection]
text = "CellForeground"
background = "#005f87"

[colors.primary]
foreground = "#e4e4e4"
background = "#3a3a3a"

[colors.normal]
black = "#303030"
red = "#af5f5f"
green = "#87af87"
yellow = "#ffd787"
blue = "#5f5faf"
magenta = "#af87af"
cyan = "#87afaf"
white = "#dadada"

[colors.bright]
black = "#767676"
red = "#af5f5f"
green = "#87af87"
yellow = "#ffd787"
blue = "#5f5faf"
magenta = "#af87af"
cyan = "#87afaf"
white = "#e4e4e4"

[bell]
animation = "EaseOutQuad"
duration = 200
color = "#000000"
